var ExtendedConnector = require('appc.swagger'),
	_ = require('lodash'),
	pkginfo = require('pkginfo')(module) && module.exports;

exports.create = function(APIBuilder, server) {
	return ExtendedConnector.create(APIBuilder, server).extend({

		/*
		 Configuration.
		 */
		pkginfo: _.pick(pkginfo, 'name', 'version', 'description', 'author', 'license', 'keywords', 'repository'),
		logger: APIBuilder.createLogger({}, { name: '${ name }', useConsole: true, level: 'debug' })

	});
};
